services:
    web:
        build:
            context: .
            args:
                RUN_UID: ${RUN_UID:-1033}
                RUN_GID: ${RUN_GID:-1033}
            target: base
        restart: unless-stopped
        volumes:
            - storage:/var/www/html/storage
            - assets:/var/www/html/assets
        environment:
            APP_NAME: "Klueterraum Papenburg e.V."
            APP_KEY: ${APP_KEY}
            APP_URL: ${APP_URL:-https://klueterraum.de}
            APP_DEBUG: ${APP_DEBUG:-false}
            APP_ENV: ${APP_ENV:-production}
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            DISCORD_GUILD: ${DISCORD_GUILD:-1038463931359957112}
            LOG_LEVEL: ${LOG_LEVEL:-error}
            LOG_STACK: 'stdout,stderr'

volumes:
    storage:
    assets:
